### ISSUE TITLE
Error in OptimizeParams

### ISSUE THREAD

**Issue by wleoncio** [SystemsBiologist/CellMigRation#20]
# Summary

I can't get this script to work. Please advise.

# Dataset

[A6dCon-short](https://github.com/ocbe-uio/CellMigRation/blob/master/inst/extdata/A6dCon-short.tif)

# Script

```r
# ==============================================================================
# Preparing package and data (OK)
# ==============================================================================
library(CellMigRation)
file_path   <- "inst/extdata/" # replace with your own location
file_name   <- "A6dCon-short.tif"
num_threads <- max(parallel::detectCores() - 2, 1)
x1          <- LoadTiff(paste0(file_path, file_name))
# ==============================================================================
# Fitting model (NOT OK)
# ==============================================================================
x1_optim <- OptimizeParams(x1, threads = num_threads)
```

# Expected result

`OptimizeParams()` finishes without errors and `x1_optim` is returned as a trackedCells object (according to `?OptimizeParams`

# Obtained result

These are the last lines of the output:

> got results for task 35
> numValues: 36, numResults: 35, stopped: TRUE
> returning status FALSE
> got results for task 36
> numValues: 36, numResults: 36, stopped: TRUE
> not calling combine function due to errors
> returning status TRUE
> <simpleError in {    message(".", appendLF = FALSE)    b <- bpass(image_array = tmp_img, lnoise = all_params$lnoise[j],         lobject = all_params$diameter[j], threshold = all_params$threshold[j])    tmpOUT <- list(img = b)    tryCatch({        pk <- suppressMessages(pkfnd(im = b, th = all_params$threshold[j],             sz = NextOdd(all_params$diameter[j])))        cnt <- suppressMessages(cntrd(im = b, mx = pk, sz = NextOdd(all_params$diameter[j])))        tmpOUT[["count"]] <- nrow(cnt)    }, error = function(e) {        tmpOUT[["count"]] <- 0    })    tmpOUT}: task 1 failed - "subscript out of bounds">
> Done!
> Error in `$<-.data.frame`(`*tmp*`, "diff100", value = integer(0)) : 
>   replacement has 0 rows, data has 36
> 
> r$> x1_optim                                                                             
> Error: object 'x1_optim' not found

# Hardware and software

- R version: 4.0.2
- Platform: x86_64-pc-linux-gnu
- CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GH (tested using 1 and 10 threads)

**Comment by dami82** [comment]
Please, retry now. It should work.

*Notes: *
- The optimization process is quite memory intensive, so going with *n_threads
= (max_threads - 2)* may be excessive. Also, note that if you are planning
to submit to CRAN, you can use up to 2 threads.

- Instead of creating a new object (namely, x1_optim), you can just to store the
optimization results in the same variable as the input. My class is designed in a way that the optimization
results are stored in a dedicated slot, while the input images are left
untouched. Therefore, you may want to keep using the same variable to store
the results (i.e., x1) unless you have a specific reason to do otherwise.

- This example may take minutes to complete. you should use a different
input if you are planning to include any of this in an example and/or
vignette.

- I have some concerns about the input TIFF. Your cells (nuclei) have a
median diameter of ~10px. Given the size of the TIFF, I would say that the
signal speckles are somewhat smaller than optimal. I guess you can still
run an analysis based on this image, but I think we should use a different
TIFF (possibly smaller and with less frames, and with a slightly higher magnification) to embed in the package as sample data.

**Comment by wleoncio** [comment]
Fixed indeed, thanks for solving this!
