### ISSUE TITLE
README.Rmd

### ISSUE THREAD

**Issue by osorensen** [SystemsBiologist/CellMigRation#7]
I added a file `README.Rmd`, which can be compiled to give `README.md`. The purpose of this is to be able to have some example code in the README file. I added a simple example as can be seen. Please edit `README.Rmd`, and then press CTRL+SHIFT+K in RStudio to generate `README.md`.

**Comment by wleoncio** [comment]
I approve of the change, though I had to adjust the "example" chunk because `README.Rmd` contained a call to `PreProcessing`, a function that doesn't seem to be part of the package (anymore? I'm too lazy to scroll through that long-@$$ file history). There are two similarly-named functions, `rmPreProcessing` and `wsaPreProcessing`. @SystemsBiologist, any clue about which one should be used?

**Comment by SystemsBiologist** [comment]
Yes, the PreProcessing() is not there anymore. I replaced it with rmPreProcessing() and wsaPreProcessing()

**Comment by wleoncio** [comment]
> Yes, the PreProcessing() is not there anymore. I replaced it with rmPreProcessing() and wsaPreProcessing()

Ok, but does it matter which one is used in the README example?

**Comment by SystemsBiologist** [comment]
Not really, but that depends on which dataset we are using:
rmPreProcessing() can be used with Trajectory_dataset
wsaPreProcessing() can be used with WSAdataset

**Comment by wleoncio** [comment]
Got it. So this issue seems settled. Closing.
