### ISSUE TITLE
cellTracker

### ISSUE THREAD

**Issue by osorensen** [SystemsBiologist/CellMigRation#8]
The package cellTracker is used by the following lines in `cellTracker_core.R`, but the package cellTracker is not listed under **Imports** in DESCRIPTION. This causes the build to fail.

    ## %dopar%
    all_results <-
      tryCatch(foreach::foreach(j = (1:nrow(all_params)),
                                .verbose = TRUE,
                                .packages = "cellTracker") %dopar% {

                                  # Verbose
                                  message(".", appendLF = FALSE)

                                  #visualize_img(tmp_img)
                                  b <- bpass(image_array = tmp_img,
                                             lnoise = all_params$lnoise[j],
                                             lobject = all_params$diameter[j],
                                             threshold = all_params$threshold[j])
                                  tmpOUT <- list(img = b)

                                  tryCatch({
                                    pk <- suppressMessages(
                                      pkfnd(im = b,
                                            th = all_params$threshold[j],
                                            sz = next_odd(all_params$diameter[j])))

                                    cnt <- suppressMessages(
                                      cntrd(im = b, mx = pk,
                                            sz = next_odd(all_params$diameter[j])))

                                    tmpOUT[["count"]] <- nrow(cnt)

                                  }, error = function(e) {
                                    tmpOUT[["count"]] <- 0

                                  })
                                  tmpOUT
                                }, error = (function(e) {
                                  print(e)
                                  try(parallel::stopCluster(cl), silent = TRUE)
                                  return(NULL)
                                }))
    message("Done!", appendLF = TRUE)
    try({suppressWarnings(parallel::stopCluster(cl))}, silent = TRUE)
  }

**Comment by SystemsBiologist** [comment]
Damiano's part was called "cellTracker" before the merging. There is no cellTracker anymore.
What do you suggest to solve this issue?
Shall we replace cellTracker with CellMigRation in that line?

**Comment by osorensen** [comment]
It might be that the namespace of the CellMigration is automatically exported to each worker, so I would test just deleting `.packages = "cellTracker"`, or alternatively changing it to `.packages = "CellMigration"`, as you suggest. I have not used foreach before, so I am not sure what is best practice when using foreach inside a package. 

One way of exploring what is common practice, is to go to the foreach package site https://cran.r-project.org/web/packages/foreach/index.html, and then look at the source code of some of the Reverse Imports. Here is one example, which suggests that changing to "CellMigration" might solve the issue: https://github.com/xuyiqing/gsynth/blob/b923e41e0c23ffddb7c92cce92b5ee4e16826d0d/R/core.R#L2411

In any case, I suggest running "R CMD CHECK" locally and making sure the package passes all tests before pushing to the master branch. I RStudio this is done with the Check button, but it can as easily be done from the command line.

**Comment by SystemsBiologist** [comment]
I adjusted that and run the check again, this is what I got:
> checking Rd metadata ... WARNING
  Rd files with duplicated alias 'CellMigRation':
    'CellMigRation-package.Rd' 'CellMigRation.Rd'

> checking data for non-ASCII characters ... WARNING
    Error loading dataset 'sample_tracked_cells':
     Error in .requirePackage(package) : 
      unable to find required package 'cellTracker'
    
    The dataset(s) may use package(s) not declared in the DESCRIPTION file.

> checking R code for possible problems ... NOTE
  cell_tracker: no visible global function definition for '%dopar%'
  optimize_params: no visible global function definition for '%dopar%'
  Undefined global functions or variables:
    %dopar%

0 errors v | 2 warnings x | 1 note x
Error: R CMD check found WARNINGs
Execution halted

Exited with status 1.

**Comment by osorensen** [comment]
This is promising!

For the %dopar% thing, R needs to know where dopar comes from. The easiest way to do this is to add
`#' @importFrom foreach %dopar%` in the Roxygen documentation to some function, and then run `devtools::document()`.

**Comment by osorensen** [comment]
The other problem is related to `CellMigration.R`:

```
#' CellMigRation package
#'
#' Contains 15 trajectory analysis functions.
#'
#' @docType package
#'
#' @author Salim Ghannoum \email{salim.ghannoum@@medisin.uio.no}
#'
#' @name CellMigRation

NULL
````

Try replacing `CellMigration` with `CellMigration-package`, and see if that works. Alternatively, just comment out the file `CellMigration.R`, run documentation again, and see if it passes then.

**Comment by osorensen** [comment]
For the dataset issue, it might be there still is a reference to cellTracker somewhere? I suggest doing a text search in the whole repository for the string "cellTracker", and carefully replacing one by one with "CellMigration" as appropriate. In Rstudio you can do this with Ctrl+Shift+F.

**Comment by dami82** [comment]
I started working on the merger yesterday.
I cloned yesterday’s version of master locally and I am working on that.
Foreach should go in the depends, as it was in my description.
Related to this, I will try to move some of your depends in the imports.
The dataset is fine. Let me take care of the parallel stuff.
I can keep working on the merger, please give me 2 days and don’t update major stuff to the repo, as the structure will change a bit. I don’t want to waste time.
Salim, do we have to export all those functions? Do you have anything worth keeping internal? I may rewrite some examples as well.
Salim, can you start working on a vignette in the meanwhile?


Best regards,
Damiano

——
Damiano Fantini

**Comment by dami82** [comment]
The dataset is an object of the class in cell tracker. I sent Salim the code to built it from scratch. No need to say that it has to be rebuilt if you change the package. Copying the rda file won’t work

Best regards,
Damiano

——
Damiano Fantini

**Comment by SystemsBiologist** [comment]
Thank you Øystein for the solutions they worked perfectly.
The only problem left is the dataset:

-- R CMD check results -------------------------------- CellMigRation 0.1.1 ----
Duration: 2m 59.3s

> checking data for non-ASCII characters ... WARNING
    Error loading dataset 'sample_tracked_cells':
     Error in .requirePackage(package) : 
      unable to find required package 'cellTracker'
    
    The dataset(s) may use package(s) not declared in the DESCRIPTION file.

0 errors v | 1 warning x | 0 notes v
Error: R CMD check found WARNINGs
Execution halted

Exited with status 1.

Damiano, could you please recreate the "sample_tracked_cells.rda" dataset so we dont get that error?
I will start start working on a vignette very soon.

Best,
Salim

**Comment by SystemsBiologist** [comment]
Shall I push the changes?

**Comment by SystemsBiologist** [comment]
Or it is better to send you Damiano the changed files by email?

**Comment by dami82** [comment]
Go ahead. I’ll download the master again tonight 

Best regards,
Damiano

——
Damiano Fantini

**Comment by SystemsBiologist** [comment]
OK

**Comment by osorensen** [comment]
Great!

**Comment by osorensen** [comment]
The Travis build failure now seems to be caused by trouble installing one of the dependencies. These things tend to be a bit tricky, and require editing the .travis.yml file. @wleoncio , maybe this is something you are good at?

Anyway, I will pull from the master branch at work tomorrow and take a new look at the package.

**Comment by SystemsBiologist** [comment]
I am sure Damiano will take care of the dependencies.

**Comment by wleoncio** [comment]
> The Travis build failure now seems to be caused by trouble installing one of the dependencies. These things tend to be a bit tricky, and require editing the .travis.yml file. @wleoncio , maybe this is something you are good at?

I've never done much customization in the `.travis.yml` file (the bare-bones default has always worked fine for me), but I could definitely try tweaking it a bit to see if we can get it to properly download the missing package (vioplot). I need to focus on other projects for the next couple of days, but I'll let y'all know as soon as I make progress on this.

**Comment by dami82** [comment]
Hi all,

Thank you guys for your hard work so far. I uploaded an updated version of
the package, you'll find it in the* DFmod* branch. I removed everything
that was not required for building/running the package. The package checked
out on my machine (ubuntu) with only one note about the examples execution
time (~5.5 sec). Feel free to pull this to master or continue upgrading the
*DFmod* branch and add whatever you want (LICENSE, README, logo, and so on).

*Changes*
I reorganized the *scr* to include 4 R files.
I took the liberty of renaming the datasets (they now have a consistent
nomenclature) and my functions (in agreement with Bioconductor reqs).
I think we should refrain from declaring all imports as stand-alone lines.
I think it is way better to declare imports for each function.
I noticed that there are parts of code that should be rewritten to improve
efficiency. I guess we can leave the code as is for now, but we should keep
this in mind.

*Notes/quesions*
*Travis* failed because it has no Display output I guess, and hence it
fails to install the dependencies: *sm* and/or *vioplot*. Even if *Travis*
reported errors while building, the package looks OK to me. Of course, I
tested *DFmod* on my Ubuntu, as well as on r-hub,io (
https://builder.r-hub.io/status/CellMigRation_0.1.1.tar.gz-086be0b5e767c85929eb3fba4ee0b9e8).
It was successful.
Is there a reason for running the Principal component analysis with PCA()
that requires 200 dependencies instead of stats::prcomp() which typically
works more than OK?
I assume you guys will get a website where to host a copy of the library
and a set of vignettes. Actually, I was (still am) planning to do the same
and add info about the package on one of my websites/blogs (I guess
data-pulse.com), so I included a placeholder URL.
Would it be possible to improve the logo? I used fiverr in the past, and
you can get decent logos for less than 50 bucks. I can chip in. What do you
guys think? I mean, you work in Norway (2nd GDP per capita in the world).

Please, let me know what you think and/or what I can do to further improve
the library..

Best regards,
Damiano













Il giorno mer 4 mar 2020 alle ore 11:59 Waldir Leoncio <
notifications@github.com> ha scritto:
